package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Service For Webchat
 * 
 *
 * This class was generated by Apache CXF 3.0.7
 * 2016-09-19T18:11:57.971+08:00
 * Generated source version: 3.0.7
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SrvWebchat")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SrvWebchat {

    @WebMethod(operationName = "Action", action = "urn:MIT_Service-SrvWebchat#Action")
    @WebResult(name = "SrvWebchat___ActionResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public SrvWebchatActionResponse action(
        @WebParam(partName = "parameters", name = "SrvWebchat___Action", targetNamespace = "http://tempuri.org/")
        SrvWebchatAction parameters
    );
}
